import Head from "next/head";
import { useState, setState } from "react";
import PetList from "../components/PetList";
// import Image from 'next/image'
import PetListForm from "../components/PetListForm";
import Footer from "../components/Footer";

export async function getStaticProps() {
  const res = await fetch("http://localhost:8888/.netlify/functions/get-pets");
  const result = await res.json();

  return {
    props: {
      pets: JSON.stringify(result),
    },
  };
}

export default function Home({ pets }) {
  const [showForm, setShowForm] = useState(false);
  const toggleShowForm = () => {
    // toggle the showForm state with setState
    setShowForm({ showForm: !showForm });
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="py-8 px-4">
        <div className="static">
          <a
            href="/"
            className="flex ml-32 mb-16 font-adelia uppercase items-center md:justify-start justify-center text-gray-900"
          >
            <img src="/favicon.png" alt="logo" className="w-10" />
            <span className="ml-3 text-xl">Pets can date</span>
          </a>

          <div className="justify-center items-center flex flex-col mt-8">
            <h1 className="sm:text-4xl text-2xl font-black mb-10 text-center w-2/4 font-pumpkin">
              Let’s get your baby hooked up with another baby! *winks winks*
            </h1>
            <p className="mb-10 opacity-70 text-base leading-relaxed text-center w-2/4 font-sfpro">
              You know how one time you met someone amazing, you bonded with
              them and became friends, eventually ya'll fell in love, yeah that
              feeling. Pets deserve it too
            </p>

            <img
              className="w-full sm:w-1/4 md:w-auto lg:w-auto xl:w-1/3 h-96  mb-10"
              alt="pet"
              src="/pet.png"
            />
          </div>
          <div>
            {/* <!-- create a circle to appear on the left of the page with a background color of red --> */}
            <div
              className="absolute top-24 -left-80 font-bold text-gray-700 bg-ecllipse rounded-full flex items-center justify-center font-sfpro h-24 w-24"
              style={{ height: "550px", width: "550px" }}
            />
          </div>
          <div>
            <div
              className="absolute top-3/4 left-3/4 font-bold text-gray-700 bg-ecllipse rounded-full flex items-center justify-center font-sfpro h-24 w-24"
              style={{ height: "550px", width: "550px" }}
            />
          </div>
        </div>
        <PetList pets={pets} />
        <Footer />
      </section>
    </div>
  );
}
